apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openpdc-adapter.fullname" . }}
  labels:
    {{- include "openpdc-adapter.labels" . | nindent 4 }}
type: Opaque
stringData:
  OpenPdc__Username: {{ .Values.openPdc.username | quote }}
  OpenPdc__Password: {{ .Values.openPdc.password | quote }}
  OpenObjects__Token: {{ .Values.openObjects.token | quote }}
